### PR TITLE
Front end PR

### PR DESCRIPTION
**Pull request by shubham-ghuge**
Please review the code and suggest me the necessary changes, to increase the code quality.
- [deploy link](https://realfarmer-quiz.netlify.app/)
- [ online vs code ](github1s.com/shubham-ghuge/real-farmer/tree/dev/)

### CODE REVIEW

**Comment by MadhushreeKunder** [comment]
1. I attempted the first category of the quiz and got only 1 correct answer. So on the results page, my score is 11.11111111111111% So maybe you can round off this value to 1 or 2 decimal places because it overflows to the adjacent blocks(Total questions and attempted0
2. suggestion: You can allow the user to change their answer instead of disabling the radio buttons after 1 selection. 
3. As mentioned above I got only 1 answer right, but on the results page, it shows that I have Attempted 1 question. So maybe you can change the naming like: 
    a. Total questions(the total number of questions you have given), 
    b. Attempted(How many questions the player has tried/attempted),(or maybe you can simply put 5/9 attempted) 
    c. Correct Answers(how many questions the player got right). 
4. I really liked the certificate part. Thoughtful!
5. After I attempted all the 3 quiz, the dashboard page/explore page only displays welcome back, john doe --->_my username. So maybe you can fix that._
@shubham-ghuge

**Comment by shubham-ghuge** [comment]
>     1. I attempted the first category of the quiz and got only 1 correct answer. So on the results page, my score is 11.11111111111111% So maybe you can round off this value to 1 or 2 decimal places because it overflows to the adjacent blocks(Total questions and attempted0
> 
>     2. suggestion: You can allow the user to change their answer instead of disabling the radio buttons after 1 selection.
> 
>     3. As mentioned above I got only 1 answer right, but on the results page, it shows that I have Attempted 1 question. So maybe you can change the naming like:
>        a. Total questions(the total number of questions you have given),
>        b. Attempted(How many questions the player has tried/attempted),(or maybe you can simply put 5/9 attempted)
>        c. Correct Answers(how many questions the player got right).
> 
>     4. I really liked the certificate part. Thoughtful!
> 
>     5. After I attempted all the 3 quiz, the dashboard page/explore page only displays welcome back, john doe --->_my username. So maybe you can fix that._
>        @shubham-ghuge

**Comment by shubham-ghuge** [comment]
>     1. I attempted the first category of the quiz and got only 1 correct answer. So on the results page, my score is 11.11111111111111% So maybe you can round off this value to 1 or 2 decimal places because it overflows to the adjacent blocks(Total questions and attempted0
> 
>     2. suggestion: You can allow the user to change their answer instead of disabling the radio buttons after 1 selection.
> 
>     3. As mentioned above I got only 1 answer right, but on the results page, it shows that I have Attempted 1 question. So maybe you can change the naming like:
>        a. Total questions(the total number of questions you have given),
>        b. Attempted(How many questions the player has tried/attempted),(or maybe you can simply put 5/9 attempted)
>        c. Correct Answers(how many questions the player got right).
> 
>     4. I really liked the certificate part. Thoughtful!
> 
>     5. After I attempted all the 3 quiz, the dashboard page/explore page only displays welcome back, john doe --->_my username. So maybe you can fix that._
>        @shubham-ghuge

hey @MadhushreeKunder ,
Thank you for taking time and reviewing the PR, i have implemented your suggestions, please have a look at it.

**Comment by MadhushreeKunder** [comment]
> > ```
> > 1. I attempted the first category of the quiz and got only 1 correct answer. So on the results page, my score is 11.11111111111111% So maybe you can round off this value to 1 or 2 decimal places because it overflows to the adjacent blocks(Total questions and attempted0
> > 
> > 2. suggestion: You can allow the user to change their answer instead of disabling the radio buttons after 1 selection.
> > 
> > 3. As mentioned above I got only 1 answer right, but on the results page, it shows that I have Attempted 1 question. So maybe you can change the naming like:
> >    a. Total questions(the total number of questions you have given),
> >    b. Attempted(How many questions the player has tried/attempted),(or maybe you can simply put 5/9 attempted)
> >    c. Correct Answers(how many questions the player got right).
> > 
> > 4. I really liked the certificate part. Thoughtful!
> > 
> > 5. After I attempted all the 3 quiz, the dashboard page/explore page only displays welcome back, john doe --->_my username. So maybe you can fix that._
> >    @shubham-ghuge
> > ```
> 
> hey @MadhushreeKunder ,
> Thank you for taking time and reviewing the PR, i have implemented your suggestions, please have a look at it.

1. yes the results page is better now.
2. In question no. 6, **6. Which of the following states do cultivate wheat?**  Shouldn't it be **do not cultivate wheat**?
3. shubham team value farmer
In my screen the score is overflowing, so you can fix that as well!
4. Last thing: > 2. suggestion: You can allow the user to change their answer instead of disabling the radio buttons after 1 selection.
Everything else looks good! 👌👌

**Pull request merged**
